rgname                 = "terraform-state-rg-yuva"
service_principal_name = "dev-yuva-spn"
keyvault_name          = "dev-yuva-kv-101"
SUB_ID = "c5e549e4-bba6-4c3e-aab5-a0e80cea5a6e"
cluster_name = "dev-yuva-cluster"
node_pool_name = "devnp"
