rgname                 = "stage-yuva-rg"
service_principal_name = "stage-yuva-spn"
keyvault_name          = "stage-yuva-kv-101"
SUB_ID = "c5e549e4-bba6-4c3e-aab5-a0e80cea5a6e"
node_pool_name = "stagenp"
cluster_name = "stage-yuva-cluster"
